# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logos',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 11, 36, 35, 86696, tzinfo=utc), max_length=200, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
