# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_logos_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='广告标题')),
                ('description', models.CharField(max_length=100, verbose_name='广告描述')),
                ('image_url', models.ImageField(upload_to='ad/%Y%m%d', verbose_name='图片路径')),
                ('play', models.BooleanField(default=False, verbose_name='是否显示')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序（从小到大）')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name_plural': '首页广告',
                'verbose_name': '首页广告',
            },
        ),
    ]
