# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20161025_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(max_length=200, verbose_name='广告描述'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=100, verbose_name='广告标题'),
        ),
    ]
