# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20161025_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(max_length=300, verbose_name='广告描述'),
        ),
    ]
