# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20161026_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 10, 25, 17, 24, 27, 702740, tzinfo=utc), max_length=100, verbose_name='广告主题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='广告标题'),
        ),
    ]
