# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20161026_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='date_publish',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 25, 17, 58, 51, 242768, tzinfo=utc), verbose_name='添加日期'),
            preserve_default=False,
        ),
    ]
