# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_ads_date_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='callback_url',
            field=models.URLField(blank=True, null=True, verbose_name='回调url'),
        ),
    ]
