# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20161026_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index', 'id'], 'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 10, 26, 9, 32, 15, 292172, tzinfo=utc), verbose_name='分类描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=999, verbose_name='排列顺序（从小到大）'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 10, 26, 9, 32, 21, 64503, tzinfo=utc), max_length=200, unique=True, verbose_name='分类标签'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='分类名称'),
        ),
    ]
