# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20161026_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('slug', models.SlugField(max_length=200, verbose_name='商品标签')),
                ('image_url', models.ImageField(blank=True, upload_to='product/%Y/%m/%d', verbose_name='图片路径')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='打折价格')),
                ('stock', models.PositiveIntegerField(verbose_name='商品货存')),
                ('available', models.BooleanField(default=True, verbose_name='商品是否有效')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ads',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='ad/%Y/%m/%d', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='logos',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='logo/%Y/%m/%d', verbose_name='图片路径'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Category'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
