# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20161026_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品牌名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='品牌标签')),
                ('description', models.TextField(verbose_name='品牌描述')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序（从小到大）')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '商品品牌',
                'verbose_name_plural': '商品品牌',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ManyToManyField(related_name='categorys', to='catalog.Brand'),
        ),
    ]
